### ISSUE TITLE
Helm chart with ServiceMonitor

### ISSUE THREAD

**Issue by ebuildy** [alxrem/prometheus-logstash-exporter#16]
Hi,

I have created a Helm chart here https://github.com/ebuildy/helm-charts-1/tree/main/charts/prometheus-logstash-exporter

You can test it:

```
    - name: prometheus-logstash-exporter
      repository: https://ebuildy.github.io/helm-charts-1
      version: v0.1.0
```

I am going to propose a PR to official https://github.com/prometheus-community/helm-charts/ repo, using your exporter, do you agree?

Thanks you,

**Comment by alxrem** [comment]
Hello.
I agree, but I have no installation to test it. I don't use logstash at this time and I never used prometheus operator.

**Comment by ebuildy** [comment]
I did the Helm chart here > https://github.com/ebuildy/helm-charts-1/tree/main/charts/prometheus-logstash-exporter for those intersted.

PR is on the way as well.

thanks you!

**Comment by ArjonBu** [comment]
@ebuildy did you delete your repo? Where can I find the helm chart for this exporter?

Thanks in advance

**Comment by LHozzan** [comment]
Hi @ArjonBu .

If you using only one Logstash instance, this helm chart is fine.
But if you using many instances (e.g. in K8s cluster), I recommend deploy this exporter as a side car to pod together with Logstash.

Hope, that @ebuildy have this heml chart somewhere. If not, let me know. I have somewhere copy from it.

Best regards.
