### ISSUE TITLE
Build a new image just to get rid of CVEs

### ISSUE THREAD

**Issue by JPLachance** [alxrem/prometheus-logstash-exporter#24]
Greetings,

When we scan the `alxrem/prometheus-logstash-exporter` container image with a tool like [Snyk](https://snyk.io/product/container-vulnerability-management/), Snyk reports a ton of vulnerabilities in this container base image:
```
Tested 14 dependencies for known issues, found 23 issues.

Base Image     Vulnerabilities  Severity
alpine:3.12.3  23               2 critical, 16 high, 3 medium, 2 low

Recommendations for base image upgrade:

Minor upgrades
Base Image   Vulnerabilities  Severity
alpine:3.13  0                0 critical, 0 high, 0 medium, 0 low
```

Here, upgrading the base image would remove a lot of noise.

On top of that, [Alpine 3.12 is reaching end of live on 01 May 2022](https://endoflife.date/alpine).

Since the [Dockerfile](https://github.com/alxrem/prometheus-logstash-exporter/blob/master/Dockerfile) is always using the latest version of alpine, all we need is to build a new image, ship it to [Docker Hub](https://hub.docker.com/r/alxrem/prometheus-logstash-exporter/tags) as a version 0.8.0, and all our security tools will stop telling us we are doing bad things.

Can we do it? I would do it myself, but I don't have access to this project CI/CD setup, nor to the Docker Hub project.

Thanks!

**Comment by LHozzan** [comment]
Hi @JPLachance .
I attempted to fix some CVEs in [this PR](https://github.com/alxrem/prometheus-logstash-exporter/pull/25).
@alxrem What do you think about it?
