### ISSUE TITLE
Report reload timestamps

### ISSUE THREAD

**Issue by michael-doubez** [alxrem/prometheus-logstash-exporter#5]
As it is, we have no way to identify if the last reload of a pipeline succeeded.

Logstash interface gives us timestamp that we can use to identify if a reload was finally resolved.
Note: it doesn't work all of the time because restoring the file to original state solves the issue but is not reported in the API.

**Comment by alxrem** [comment]
If you only need to detect failures of pipline reload, you should check `rate(logstash_reloads_failures)` metric. If you have autoreload enabled, `logstash_reloads_failures` will grow until you fix pipeline. If you reloading logstash by signal, you may check `max_over_time(rate(logstash_reload_failures)) > 0` during interval which is enough to trigger alert.

**Comment by alxrem** [comment]
I added parsing of values of type timestamp. Thank you.
You are welcome to test new metrics.
