### ISSUE TITLE
[enhancement] proposed pre-compiled packages in release

### ISSUE THREAD

**Issue by michael-doubez** [alxrem/prometheus-logstash-exporter#8]
Hello,

Would you consider uploading pre-compiled packages in GitHub releases ?
It would be convenient to be able to download them rather than rebuilding.

That's quite easy to do with https://github.com/tcnksm/ghr. Something like the following:

    # Cross build you project for various arch + generate tar.gz packages
    # ... <choose your poison for that> ...
    # upload packages to release
    go get github.com/tcnksm/ghr
    VERSION=....<whatever you do to inject it in your build>...
    ghr -t ${GITHUB_TOKEN} -u ${USERNAME} -r ${PROJECT_REPONAME} -c ${SHA1} -delete ${VERSION} ./path/to/dist/packages/

And you can then add a stat shield on you readme:

     [![GitHub All Releases](https://img.shields.io/github/downloads/alxrem/prometheus-logstash-exporter/total)][releases]
    
     [releases]: https://github.com/alxrem/prometheus-logstash-exporter/releases

**Comment by No1zzz** [comment]
Builds for fresh ubuntu? 18.04?

**Comment by michael-doubez** [comment]
The usual flavors are OS=darwin/linux/windows with ARCH=amd64.
You can cross-compile with

`GOOS=linux GOARCH=amd64 go build -ldflags "$(LDFLAGS)" -o logstash-exporter-linux-amd64/logstash-exporter ./...`

**Comment by alxrem** [comment]
> Builds for fresh ubuntu? 18.04?

Package of version 0.6.1 for Bionic is uploaded to Packagecloud.

**Comment by alxrem** [comment]
> Would you consider uploading pre-compiled packages in GitHub releases ?

I uploaded binaries, but to the [Gitlab releases page](https://gitlab.com/alxrem/prometheus-logstash-exporter/-/releases). In fact I work at Gitlab. Repository on Github is only the mirror.

**Comment by alxrem** [comment]
Published binaries of [release 0.6.2](https://github.com/alxrem/prometheus-logstash-exporter/releases/tag/0.6.2)
